import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import NavComponent from "@/components/app/navbar";
import { ThemeProvider } from "next-themes";


const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-space-grotesk',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="">
      <head />
      <body className="antialiased flex overflow-x-hidden dark:bg-black bg-white">
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme') || 'dark';
                  if (theme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
        >

          <div className="flex dark:bg-black bg-white w-full">
            <div className=" w-[13vw]">
              <div className=" fixed left-0 top-0 flex w-[13vw] justify-end items-end">
                <NavComponent />
              </div>

            </div>

            <div className=" mx-auto flex-1">
              {children}
            </div>
          </div>


        </ThemeProvider>
      </body>
    </html>
  );
}
